function [post1, post2] = MRFPostIter(Im, mu, sig2, tumorMean, ...
    tumorVar, prior, Neigh1, Neigh2, Beta)
%The following function calculates one iteration of a Markov random field
%posterior
    GammaLab1 = (prior(1) * exp(-Beta * Neigh1)) ./ ...
        (prior(1) * exp(-Beta * Neigh1) + prior(2) * exp(-Beta * Neigh2));
    GammaLab2 = prior(2) * exp(-Beta * Neigh2) ./ ...
        (prior(1) * exp(-Beta * Neigh1) + prior(2) * exp(-Beta * Neigh2));
    post1 = normpdf(Im, tumorMean, sqrt(tumorVar)) .* GammaLab1 ./ ...
        (normpdf(Im, tumorMean, sqrt(tumorVar)) .* GammaLab1 + ...
        normpdf(Im, mu, sqrt(sig2)) .* GammaLab2);
    post2 = normpdf(Im, mu, sqrt(sig2)) .* GammaLab2 ./ ...
        (normpdf(Im, tumorMean, sqrt(tumorVar)) .* GammaLab1 + ...
        normpdf(Im, mu, sqrt(sig2)) .* GammaLab2);
end