function n = numberOfDifferentNeighbours(d)
%The following function takes a distribution matrix and calculates the
%number of "differently" assigned neighbours
    nonPadded = 1 - d;
    padded = zeros(size(nonPadded) + 2);
    padded(2:end-1, 2:end-1) = nonPadded;
    n = ...
        padded( [ 2 : end-1 ] - 1, [ 2 : end-1 ] ) + ...
        padded( [ 2 : end-1 ] + 1, [ 2 : end-1 ] ) + ...
        padded( [ 2 : end-1 ], [ 2 : end-1 ] + 1 ) + ...
        padded( [ 2 : end-1 ], [ 2 : end-1 ] - 1 ) + ...
        padded( [ 2 : end-1 ] - 1, [ 2 : end-1 ] - 1 ) + ...
        padded( [ 2 : end-1 ] + 1, [ 2 : end-1 ] - 1 ) + ...
        padded( [ 2 : end-1 ] - 1, [ 2 : end-1 ] + 1 ) + ...
        padded( [ 2 : end-1 ] + 1, [ 2 : end-1 ] + 1 );
end